# --- General options --- #

# Name of website
title: © Jürgen Pointinger

# email: your-email@example.com

# Short description of your site
description: >- # this means to ignore newlines until "baseurl:"
  A blog about DevOps, Agility, Software Development Practices, Coding and Management 3.0.
  Created by Jürgen Pointinger, a Consultant for Software Development Life Cycle (SDLC),
  Technical Agile Coach, DevOps Advocate, Facilitator and Catalyst.

# --- Local development options ---
# If your website is hosted locally rather than on GitHub, then you need to uncomment the next two parameters to set the url and baseurl
# *** If you're not sure what this mean, then leave this section as it is. Only modify the url and baseurl if you know what you're doing!***

# url is the the website domain URL without a trailing slash
url: "https://juergenpointinger.github.io"

# baseurl should be an empty string
#baseurl: ""

permalink: /:title/

theme: jekyll-theme-primer

# --- Misc --- #

# Image to show in meta tags - image must be a square (width = height)
avatar: /assets/images/2.0/avatar.jpg

# Shortcut Icon (svg)
favicon: /assets/images/2.0/logo_light.svg

# --- Footer options --- #

# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Jürgen Pointinger
  twitter: pointij
  github: juergenpointinger

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
# gtag: "UA-163914938-1"
  
# --- Don't need to touch anything below here (but you can if you want) --- #

# Exclude these files from production site
exclude:
  - .jekyll-cache/
  - node_modules/
  - gemfiles/
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
  - logo.psd
  - transformational-leadership-model.psd
  - diagrams.pptx

plugins:
  - jekyll-feed